@{
    # Script module generated by Copilot
    RootModule = 'CadoBatchAnalysis.psm1'
    ModuleVersion = '1.0.0'
    GUID = 'a1b2c3d4-e5f6-7890-1234-567890abcdef' # A unique identifier for the module
    Author = 'Cado-Batch Project'
    CompanyName = 'Unknown'
    Copyright = '(c) 2025 Cado-Batch Project. All rights reserved.'
    Description = 'A module for post-collection forensic analysis of data gathered by Cado-Batch.'
    PowerShellVersion = '5.1'
    FunctionsToExport = @(
        'Invoke-YaraScan',
        'Invoke-EventLogParsing',
        'Search-EventLogData',
        'Invoke-MFTParsing',
        'Search-MFTForPaths',
        'Invoke-PrefetchAnalysis',
        'Invoke-RegistryAnalysis',
        'Invoke-BrowserAnalysis',
        'Invoke-NetworkAnalysis',
        'Invoke-ADAnalysis',
        'Generate-InvestigationReport',
        'Generate-Reports'
    )
    CmdletsToExport = @()
    VariablesToExport = '*'
    AliasesToExport = @()
}
